import React from 'react'

const About = () => {
  return (
    <div>
      <h1>About Us</h1>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sit iusto perspiciatis esse vero iure eaque quos vel officia, voluptate cumque distinctio natus eligendi illo molestias, accusamus dolor autem assumenda hic laborum nesciunt aliquid non ea nihil? Adipisci autem incidunt dolor omnis eaque tempore quas nemo. Inventore, veniam officiis voluptatibus quia laboriosam quasi blanditiis possimus, non, illo nesciunt iure officia saepe libero accusamus. Maxime fugiat nam numquam animi. Odio eius a, accusamus, nostrum illo, quam consequatur quidem magnam minima modi maxime tenetur! Fugit nisi, tempora at obcaecati, dignissimos nulla assumenda, dolor recusandae quia illo blanditiis quasi suscipit minus dolorum autem vitae cupiditate? Dolor aliquid iure officiis, ex laudantium rerum alias et? Reiciendis officia ullam soluta ipsa aperiam quo tenetur nobis perspiciatis a cumque molestias ab qui sapiente quibusdam, facilis eaque ratione ipsum perferendis corporis veniam eius voluptate? Quam dolorum distinctio nisi quasi facere dolorem. Assumenda, veniam magnam! Nihil consectetur illum nostrum vel sit cum distinctio iure, repellat dignissimos magni quo eos? Nesciunt est quae, sed voluptas quis non laboriosam quam esse expedita alias asperiores in quibusdam vero quisquam eos possimus facilis, impedit magnam laudantium id? Accusamus dolorem cupiditate soluta hic. Optio molestias ipsam minima magnam voluptates, nihil consequatur, quas quibusdam incidunt quis voluptate tenetur labore fuga porro temporibus perspiciatis deserunt excepturi nisi cum eos, totam ex. Dolores sunt nihil totam repellendus, modi officiis iste voluptate molestias quibusdam aut! Suscipit accusantium ipsam modi ex! Quibusdam rerum nulla quos eaque atque corporis soluta consequuntur debitis ipsa quam pariatur optio explicabo repellendus nesciunt, corrupti minus dolores expedita ea quaerat? Eligendi mollitia, est, iste animi eum cumque quas dicta numquam saepe aliquam, deserunt suscipit nisi corrupti quasi placeat molestiae iure optio doloribus similique. Quam eaque magni quisquam earum vel in tenetur reprehenderit ipsa qui! Alias nihil repudiandae expedita consequuntur iusto deserunt repellendus quis cumque suscipit exercitationem perspiciatis necessitatibus earum, inventore provident, consectetur iste, eos obcaecati quae repellat magni sit facere. Dolores adipisci laudantium sit harum tenetur nihil fuga vitae optio quod reiciendis, odio quasi aut consequuntur? A corporis, vitae pariatur provident est, hic at omnis blanditiis eligendi quia deleniti tempore accusamus dolorem quasi voluptas. Repellat eius dolores temporibus tenetur alias eligendi aperiam sed est culpa hic expedita vitae quisquam enim, natus facilis doloremque inventore distinctio delectus possimus a pariatur itaque? Est, maxime nihil labore non qui neque numquam ad totam quisquam corporis. Eos asperiores magnam voluptatem incidunt vitae odio accusantium, eius voluptatum quam? Expedita, nemo.</p>
    </div>
  )
}

export default About
