import React from 'react'

const ContactUs = () => {
  return (
    <div>
      <h1>Contact Us</h1>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Distinctio possimus quos nemo perferendis quo autem earum omnis aut est obcaecati! Sint iure maxime eius nemo accusantium aperiam totam quam reiciendis eos necessitatibus laudantium nisi sit, dignissimos rerum veritatis sed molestias atque quisquam, earum repellat. Nulla omnis fuga neque amet ex, mollitia aspernatur placeat dicta aliquam provident obcaecati error iste perferendis odio consequuntur dolor? Doloremque, voluptas voluptate! Suscipit quibusdam ratione inventore, dolorem tempore tenetur dolore minima quo aut rerum illo? Eos ullam quod expedita quae laborum sed vitae optio nobis quo, facilis dolorem similique repellendus itaque amet voluptates dolore doloremque veniam! Non ea possimus facilis assumenda obcaecati. Vel fugiat architecto nisi eveniet minima quis nesciunt, exercitationem voluptates iste incidunt labore nulla ea tempore facilis commodi! Vel numquam quia repellat libero totam eligendi officia mollitia molestiae cum nisi aperiam corporis facere, deserunt qui, at excepturi voluptates? Porro commodi suscipit ratione blanditiis nobis itaque eius similique amet, beatae quod? Iste eos earum illum reprehenderit itaque eius assumenda, quibusdam ea id molestiae porro labore, quo aut debitis placeat maxime iure animi aliquid inventore asperiores saepe beatae minima? Ducimus maiores distinctio vel odit cupiditate blanditiis, quidem ab numquam rem debitis molestiae! Praesentium ut sint qui fugiat cupiditate, itaque voluptate aut saepe iure veritatis laudantium exercitationem reprehenderit amet, debitis vel minus perferendis, dolor eveniet obcaecati quo iusto eos dolorum esse omnis? Numquam, expedita modi odit fuga eius illum tenetur laborum impedit reiciendis eligendi consectetur ullam porro, veniam sunt, aut explicabo hic. Quod at incidunt consectetur voluptatibus placeat. Omnis veniam sequi, repellat in incidunt molestias. Voluptas velit voluptate amet molestiae atque sequi, omnis provident magnam, quo tempore quis beatae tenetur molestias est obcaecati rem recusandae incidunt? Repudiandae, magni, error obcaecati possimus alias saepe repellat hic accusamus fugit repellendus voluptates dolor quasi ab ea sed? In officiis iste maxime quibusdam asperiores quas a voluptatem harum numquam alias nam rem voluptate ex, expedita tempore quia? Iusto aspernatur sint minima perferendis doloremque fugit quibusdam, alias neque. Tenetur totam aliquam consectetur, unde, saepe ex cupiditate nihil nulla architecto explicabo ab necessitatibus quas quam veritatis. Facere modi debitis inventore quibusdam laborum ut delectus exercitationem non animi quidem incidunt ab quaerat, quia voluptatum, at eius atque consequuntur harum beatae corrupti. Ducimus necessitatibus praesentium sed veritatis itaque quae officia sint eius vero esse sit iste cupiditate soluta rem, dolorem quaerat nobis suscipit ut dolor. Repellat, dolores. Odio praesentium quas dolores, doloribus laboriosam animi magni.</p>
    </div>
  )
}

export default ContactUs
